### PR TITLE
Create User page

### PR DESCRIPTION
**Pull request by marymcdonald**
Created a form for users to create an account with. It asks for a username and password, and does basic validation on them – 1) not empty and 2) username > 2 chars, password > 7 chars (these are arbitrary, but I felt I need to put some sort of lower bound?).

Added the `create-user` route and put in a fake url to call the backend with (it's `api/users` for now; will update once Jacob's PRs are merged).

### CODE REVIEW

**Comment by marymcdonald** [comment]
Route `api/users` with a POST request now tested. User was successfully created in DB.

Screenshot 2023-11-02 at 6 08 22 PM

Screenshot 2023-11-02 at 6 08 16 PM

**Comment by marymcdonald** [comment]
Not sure if I have to do anything with the jwt returned in the response at this time. Maybe for another PR.

**Comment by Jacob-Clark-809** [comment]
> Not sure if I have to do anything with the jwt returned in the response at this time. Maybe for another PR.

Yeah think on another PR makes sense. I'm about to get started on altering the API routes to require a jwt (or, eventually, the API key) - so the frontend will need to pass that along with each request it makes.

**Review by Jacob-Clark-809 — APPROVED** [review]
Looks great!

**Pull request merged**
